const responseMessages = {
  USER_REGISTERED: "User Registered Successfully",
  EMAIL_ALREADY_TAKEN: "Email is already taken",
  UNAUTHORIZED_USER: "Unauthorized - User not found",
  INCORRECT_PASSWORD: "Incorrect password",
  LOGIN_SUCCESSFUL: "LogIn Successfully",
  INCORRECT_MAIL: "Incorrect Email",
  MAIL_NOT_REGISTERED: "Email is not registered with us",
  INCORRECT_TOKEN: "Incorrect Token",
  PASSWORD_UPDATED: "password update successfully",
  TOKEN_EXPIRED: "Your reset password token is expired, please try again",
  PROFILE_FORM_SUBMITTED: "Profile created",
  SOMETHING_WRONG: "Something went wrong !",
  TOKEN_NOT_FOUND: "Please Login to access this resource",
  UNAUTHORIZED: "Unauthorized",
  VEHICLE_ADDED: "Vehicel added successfully",
  VEHICLE_UPDATED: "Vehicel updated successfully",
  VEHICLE_DELETED: "Vehicle deleted successfully",
  USER_PROFILE_FETCHED: "User profile fetched successfully",
  IMAGE_UPLOADED: "Image Uploaded successfully",
  VEHICLE_NOT_FOUND: "Vehicle not found",
  IMAGE_REMOVED: "Image removed",
  VEHICLE_IMAGE_NOT_FOUND: "Vehicle image not found",
  PROFILE_NOT_FOUND: "Profile not found",
  PROFILE_IMAGE_NOT_FOUND: "Profile image not found",
  PROFILE_PICTURE_REMOVED: "Profile picture removed successfully",
  RIDE_CREATED: "Your ride has been created successfully",
  AVAILABLE_RIDES_FETCHED: "Available rides list is fetched successfully",
  VEHICLES_FETCHED_SUCCESSFULLY: "Vehicles are fetched successfully",
  NO_RIDES_FOUND: "There are rides not available yet between these cities",
  BOOKING_REQUEST_CREATED: "Booking request created successfully",
  SEATS_ARE_NOT_AVAILABLE: "No of seates are less than your requirement",
  RIDE_IS_FULL: "Ride is full no more seats are available ",
  BOOKING_REQUEST_ACCEPTED: "Your booking request accepted",
  PROFILE_UPDATED: "Profile updated successfully",
  RIDE_NOT_FOUND: "Ride not found",
  CANNOT_UPDATE_A_RIDE: "You can't update this trip.",
  CANNOT_CANCEL_A_RIDE: "You can't cancel this ride.",
  RIDE_UPDATED: "Ride updated successfully",
  CANCEL_OFFERED_RIDE: "You cancelled your offered ride",
  CANCEL_REQUESTED_RIDE: "Your requested ride is cancelled",
  INCORRECT_OLD_PASSWORD: "Incorrect old password",
  RIDE_STATUS_ACCEPTED: "Your ride has been accepted",
  RIDE_STATUS_REJECTED: "Your ride has been rejected",
  RIDES_LIST_FETCHED: "Rides list is fetched successfully",
  RIDES_NOT_FOUND: "Rides not found",
  CREATED_RIDE_REQUESTS_NOT_FOUND:
    "You don't have any request for your created rides.",
  CREATED_RIDE_REQUESTS_LIST_FETCHED:
    "You've successfully retrieved the list of booking requests from users",
  BOOKED_RIDE_REQUESTS_NOT_FOUND:
    "You don't have any request for your booked rides.",
  BOOKED_RIDE_REQUESTS_LIST_FETCHED:
    "You've successfully retrieved the list of your booking requests",
  RIDE_REQUEST_NOT_EXIST: "This ride request doesn't exist",
  RIDE_REQUEST_UPDATED: "Ride request updated successfully",
  RIDE_REQUEST_CREATED: "Ride request created successfully",
  RIDE_REQUEST_ALREADY_CREATED:
    "You've already created an alert for this ride and date.",
  RIDE_REQUEST_CANCELLED: "Your ride request is cancelled",
};

module.exports = responseMessages;
